"""Declarative base, mixins and column conventions.

Everything the schema repeats lives here once. Three conventions are enforced
for every table (docs/TDD.md section 7.2):

* a UUID v4 primary key generated by the database, so an id is never guessable
  and a client can never collide with one;
* ``created_at``, and ``updated_at`` where a row is mutable;
* an explicit naming convention for constraints and indexes, so Alembic
  autogenerate produces stable names and a migration can drop a constraint it
  did not create.
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Without this, Postgres invents constraint names and a downgrade cannot find
#: them. Alembic's own documentation calls an explicit convention a
#: prerequisite for reliable migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy reads this as a class attribute
        dict[str, Any]: JSONB,
        dt.datetime: DateTime(timezone=True),
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated server-side by ``gen_random_uuid()`` (pgcrypto)."""
    return mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def fk_uuid(*args: Any, **kwargs: Any) -> Mapped[uuid.UUID]:
    """A foreign-key column. Always indexed: every FK in this schema is joined on."""
    return mapped_column(PgUUID(as_uuid=True), *args, index=True, **kwargs)


class TimestampMixin:
    """``created_at`` on every row, defaulted by the database.

    Server-side rather than application-side so a row inserted by a migration,
    a backfill or psql carries a real timestamp too.
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )


class UpdatedAtMixin:
    """``updated_at`` for mutable rows.

    ``onupdate`` is application-side on purpose: a database trigger would fire
    on writes the ORM does not know about, and the two would disagree.
    """

    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
