"""How much weight a source's *origin* earns, before anything it says is read.

This is not a judgement of the content. Nothing here reads the document; it
looks at where the bytes came from and answers two questions a reader of a
citation asks first: is this the thing itself or commentary about it, and is the
publisher the kind of place that is accountable for being wrong.

**It is a declared table, not a model.** Every score below is a constant with a
stated reason, so a source's number can be explained to the person reading the
report and changed by editing one line. A learned reputation score would be a
number nobody could account for attached to a citation, which is the opposite of
what this product is for.

**It is deliberately coarse.** Four tiers, and the score is the tier. A finer
scale would imply a precision that the inputs - a URL and a source type - cannot
support. What it must never do is guess upward: an unrecognised domain is
``unknown`` and scores below a community forum, because "we do not know who runs
this" is worse than "we know, and it is a forum".

``is_primary`` is the field the UI shows most prominently, and it is decided by
how the source was obtained rather than by what it looks like: a filing came
through the SEC tool, a paper through arXiv, a repository through GitHub, an
upload from the user. A web page is primary only when its registrable domain is
the one making the statement, which this cannot know, so a web page is not
primary. Understating it is the safe direction - a reader who is told a source
is primary stops checking.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from app.core.enums import SourceType
from app.sources.urls import registrable_domain

Tier = Literal["official", "reputable", "community", "unknown"]

#: The score each tier carries. The tier *is* the score - there is no per-domain
#: adjustment - so two sources shown with the same badge always have the same
#: number, and a reader who learns what one badge means has learned them all.
TIER_SCORES: dict[Tier, float] = {
    "official": 0.90,
    "reputable": 0.75,
    "community": 0.55,
    #: Below community on purpose. An unrecognised registrar is not a neutral
    #: 0.5; it is the absence of any reason for confidence.
    "unknown": 0.40,
}

#: Suffixes whose registration is restricted and whose registrant is therefore
#: identifiable and accountable. Matched on the registrable domain's suffix, so
#: ``sec.gov`` and ``treasury.gov`` are both covered without listing either.
_OFFICIAL_SUFFIXES = (".gov", ".mil", ".int", ".edu", ".ac.uk", ".gov.uk", ".europa.eu")

#: Places that publish under a masthead with a correction policy. Short and
#: explicitly incomplete: this list decides a badge, not whether a source is
#: used, and every domain absent from it still appears with its own name shown.
_REPUTABLE_DOMAINS = frozenset(
    {
        "reuters.com",
        "apnews.com",
        "bloomberg.com",
        "ft.com",
        "wsj.com",
        "nytimes.com",
        "economist.com",
        "nature.com",
        "science.org",
        "ieee.org",
        "acm.org",
    }
)

#: User-generated by design. Not a penalty - a repository's issue thread is often
#: the only place a defect is described - but a reader should know which it is.
_COMMUNITY_DOMAINS = frozenset(
    {
        "reddit.com",
        "news.ycombinator.com",
        "stackoverflow.com",
        "stackexchange.com",
        "medium.com",
        "substack.com",
        "x.com",
        "twitter.com",
        "quora.com",
    }
)


@dataclass(frozen=True, slots=True)
class Credibility:
    """One source's origin assessment, as the ``sources`` row stores it."""

    score: float
    tier: Tier
    is_primary: bool
    notes: str | None

    def as_metadata(self) -> dict[str, object]:
        """Exactly the ``SourceCredibility`` DTO's shape.

        The column is read straight into that model, which forbids unknown
        fields, so anything else written here would turn the sources endpoint
        into a 500 the moment a real row existed. Building it from this one
        place is what keeps the writer and the reader agreeing.
        """
        return {
            "is_primary": self.is_primary,
            "tier": self.tier,
            "domain_reputation": self.score,
            "notes": self.notes,
        }


def assess(source_type: SourceType, domain: str) -> Credibility:
    """What this source's origin is worth, from its type and its domain."""
    registrable = registrable_domain(domain)
    match source_type:
        case SourceType.SEC:
            return Credibility(
                score=TIER_SCORES["official"],
                tier="official",
                is_primary=True,
                notes="Filed with the SEC",
            )
        case SourceType.ARXIV:
            # Primary because it is the authors' own paper, and explicitly
            # labelled because a preprint has passed no review - a distinction
            # that matters more than the score and is lost if only the score
            # is shown.
            return Credibility(
                score=TIER_SCORES["reputable"],
                tier="reputable",
                is_primary=True,
                notes="Preprint, not peer reviewed",
            )
        case SourceType.GITHUB:
            return Credibility(
                score=TIER_SCORES["community"],
                tier="community",
                is_primary=True,
                notes="Repository metadata",
            )
        case SourceType.UPLOAD:
            # Provided by the person asking the question. Its accountability is
            # theirs, and the system has no way to assess it - so it is not
            # scored as if it had been found.
            return Credibility(
                score=TIER_SCORES["unknown"],
                tier="unknown",
                is_primary=True,
                notes="Supplied with the request",
            )
        case SourceType.WEB:
            return _web(registrable)


def _web(registrable: str) -> Credibility:
    """A fetched page, judged only by who is accountable for the domain."""
    if registrable.endswith(_OFFICIAL_SUFFIXES):
        return Credibility(
            score=TIER_SCORES["official"],
            tier="official",
            is_primary=False,
            notes="Restricted-registration domain",
        )
    if registrable in _REPUTABLE_DOMAINS:
        return Credibility(
            score=TIER_SCORES["reputable"], tier="reputable", is_primary=False, notes=None
        )
    if registrable in _COMMUNITY_DOMAINS:
        return Credibility(
            score=TIER_SCORES["community"],
            tier="community",
            is_primary=False,
            notes="User-generated content",
        )
    return Credibility(score=TIER_SCORES["unknown"], tier="unknown", is_primary=False, notes=None)
